service: escudosbackend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  profile: escudosfiscales

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
    events:
      - httpApi:
          method: get
          path: /second
  tercero:
    handler: handler.hello
    events:
      - httpApi:
          method: get
          path: /tercero
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: "*" # <-- Specify allowed origin
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Startlower
              - Text
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
